import React, { useState, useEffect } from 'react'
import { api, StatusBadge } from '../shared'
import { toast } from 'react-hot-toast'
import ReactMarkdown from 'react-markdown'
import { useEventConfig } from '../EventContext'

function AnalyticsTab() {
  const [posts, setPosts] = useState([])
  const [loading, setLoading] = useState(true)

  // We assign mock metrics to posts to keep them stable during render
  const generateMockMetrics = () => ({
    twitter:   { impressions: Math.floor(Math.random()*500)+200, likes: Math.floor(Math.random()*50)+10, retweets: Math.floor(Math.random()*20)+2 },
    linkedin:  { impressions: Math.floor(Math.random()*300)+100, clicks: Math.floor(Math.random()*30)+5,  reactions: Math.floor(Math.random()*40)+8 },
    instagram: { reach: Math.floor(Math.random()*400)+150,       likes: Math.floor(Math.random()*60)+15,  comments: Math.floor(Math.random()*10)+1 }
  })

  useEffect(() => {
    api.get('/api/outputs/posts')
      .then(r => {
        const withMetrics = (r.data.posts || []).map(p => ({
          ...p,
          metrics: generateMockMetrics()
        }))
        setPosts(withMetrics)
      })
      .catch(() => {})
      .finally(() => setLoading(false))
  }, [])

  // Increment metrics every 30 seconds
  useEffect(() => {
    const interval = setInterval(() => {
      setPosts(prev => prev.map(p => {
        if (!p.approved) return p
        return {
          ...p,
          metrics: {
            ...p.metrics,
            twitter: { ...p.metrics.twitter, impressions: p.metrics.twitter.impressions + Math.floor(Math.random()*5) },
            linkedin: { ...p.metrics.linkedin, impressions: p.metrics.linkedin.impressions + Math.floor(Math.random()*5) },
            instagram: { ...p.metrics.instagram, reach: p.metrics.instagram.reach + Math.floor(Math.random()*5) }
          }
        }
      }))
    }, 30000)
    return () => clearInterval(interval)
  }, [])

  const handlePublish = async (run_id) => {
    try {
      await api.post('/api/swarm/approve-post', { run_id })
      setPosts(prev => prev.map(p => p.run_id === run_id ? { ...p, approved: true } : p))
      toast.success('Post published to mock social feeds!')
    } catch (err) {
      toast.error('Failed to publish post')
    }
  }

  if (loading) return <div className="output-terminal" style={{ padding: 24, textAlign: 'center', color: 'var(--text-muted)' }}>Loading analytics…</div>
  if (!posts.length) return <div className="output-terminal" style={{ padding: 24, textAlign: 'center', color: 'var(--text-muted)' }}>No generated posts yet. Use the Generative Strategist to build content.</div>

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      {posts.map((p, i) => (
        <div key={i} className={`history-card ${p.approved ? 'approved' : 'pending'}`} style={{ border: p.approved ? '1px solid var(--green)' : '1px solid var(--border)' }}>
          <div className="history-meta" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div>
              {new Date(p.timestamp).toLocaleString()} — <em>{p.triggered_by?.slice(0, 60) || 'Autogenerated'}</em>
              {p.approved && (
                <span className="badge" style={{ marginLeft: 8, fontSize: 10, background: 'rgba(0,230,118,0.2)', color: 'var(--green)', border: '1px solid var(--green)' }}>
                  ● LIVE
                </span>
              )}
            </div>
            {!p.approved && (
               <button className="btn-primary" style={{ padding: '4px 12px', fontSize: '12px' }} onClick={() => handlePublish(p.run_id)}>
                 Publish
               </button>
            )}
          </div>
          <div className="history-body" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: 16, marginTop: 16 }}>
            {Object.entries(p.posts || {}).map(([platform, text]) => (
              <div key={platform} className="output-terminal" style={{ display: 'flex', flexDirection: 'column', background: 'var(--bg-card)' }}>
                <div style={{ color: 'var(--text-normal)', fontWeight: 600, fontSize: 12, marginBottom: 8, textTransform: 'capitalize', display: 'flex', alignItems: 'center', gap: 6 }}>
                  <span className="material-symbols-outlined" style={{ fontSize: 16 }}>{platform === 'twitter' ? 'tag' : platform === 'instagram' ? 'photo_camera' : 'work'}</span>
                  {platform}
                </div>
                <div style={{ flexGrow: 1, maxHeight: 120, overflow: 'auto', marginBottom: 16, fontSize: '13px', color: 'var(--text-secondary)' }}>
                  <ReactMarkdown>{text}</ReactMarkdown>
                </div>
                {p.approved && p.metrics && p.metrics[platform] && (
                  <div style={{ display: 'flex', gap: 12, borderTop: '1px solid var(--border)', paddingTop: 12, fontSize: '12px' }}>
                    {Object.entries(p.metrics[platform]).map(([metricName, value]) => (
                      <div key={metricName} style={{ display: 'flex', flexDirection: 'column' }}>
                        <span style={{ color: 'var(--text-muted)', textTransform: 'uppercase', fontSize: '9px' }}>{metricName}</span>
                        <span style={{ color: 'var(--text-normal)', fontWeight: 600, fontSize: '14px' }}>{value.toLocaleString()}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      ))}
    </div>
  )
}



export default function ContentPage() {
  const [tab, setTab] = useState('generate')
  const [eventName, setEventName] = useState('')
  const [description, setDescription] = useState('')
  const [audience, setAudience] = useState('')
  const [status, setStatus] = useState('idle')
  const [results, setResults] = useState(null)
  const [hasPrefill, setHasPrefill] = useState(false)

  useEffect(() => {
    try {
      const saved = localStorage.getItem('swarm_event_config')
      if (saved) {
        const config = JSON.parse(saved)
        setEventName(config.eventName || '')
        setDescription(config.description || '')
        setAudience(config.targetAudience || '')
        setHasPrefill(true)
      }
    } catch (e) {}
  }, [])

  const handleGenerate = async () => {
    if (!eventName || !description) return toast.error('Fill required fields')
    setStatus('running')
    setResults(null)
    try {
      const payload = { event_name: eventName, raw_text: description, target_audience: audience }
      const response = await api.post('/api/content', payload)
      setResults(response.data)
      setStatus('done')
      toast.success('Content Generated')
    } catch (err) {
      console.error(err)
      setStatus('error')
      toast.error('Failed to generate content')
    }
  }

  return (
    <div>
      <div className="page-header-card">
        <div>
          <h2 className="page-header">Content Strategist</h2>
          <p className="page-subtitle" style={{ margin: 0 }}>Create compelling copy tailored to your audience.</p>
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '8px' }}>
          <span className="badge" style={{ background: 'var(--bg-input)', border: '1px solid var(--border)' }}>AGENT 1 OF 3</span>
          <StatusBadge status={status} />
        </div>
      </div>

      <div className="tab-row">
        <button className={`tab-btn ${tab === 'generate' ? 'active' : ''}`} onClick={() => setTab('generate')}>Generate</button>
        <button className={`tab-btn ${tab === 'analytics' ? 'active' : ''}`} onClick={() => setTab('analytics')}>Analytics Feed</button>
      </div>

      {tab === 'generate' ? (
        <>
          {hasPrefill && <div className="prefill-banner">✓ Pre-filled from your Event Setup — edit if needed</div>}
          <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0,1fr) minmax(0,1.2fr)', gap: '32px' }}>
            <div className="agent-card" style={{ height: 'fit-content' }}>
              <div className="form-group">
                <label className="form-label">Event Name</label>
                <input className="form-input" value={eventName} onChange={e => setEventName(e.target.value)} placeholder="e.g. Neurathon '26" />
              </div>
              <div className="form-group">
                <label className="form-label">Target Audience</label>
                <input className="form-input" value={audience} onChange={e => setAudience(e.target.value)} placeholder="e.g. AI Researchers, Developers" />
              </div>
              <div className="form-group">
                <label className="form-label">Event Description & Brief</label>
                <textarea className="form-textarea" value={description} onChange={e => setDescription(e.target.value)} placeholder="Provide key details, dates, and selling points..." />
              </div>
              <button className="btn-primary" style={{ width: '100%', marginTop: '8px' }} onClick={handleGenerate} disabled={status === 'running'}>
                <span className="material-symbols-outlined">play_arrow</span>
                {status === 'running' ? 'Generating...' : 'Generate Content'}
              </button>
            </div>
            <div>
              <h3 className="section-title">Generation Results</h3>
              {results ? (
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                  {['twitter', 'linkedin', 'instagram', 'posting_schedule'].map(key => (
                    <div className="output-terminal" style={{ maxHeight: '200px', overflow: 'auto' }} key={key}>
                      <div style={{ color: 'var(--text-secondary)', fontSize: '10px', marginBottom: '8px', textTransform: 'uppercase' }}>{key.replace('_', ' ')}</div>
                      <pre style={{ whiteSpace: 'pre-wrap', margin: 0, fontFamily: 'inherit', fontSize: 'inherit' }}>
                        {typeof results[key] === 'object' ? JSON.stringify(results[key], null, 2) : (results[key] || '...')}
                      </pre>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="output-terminal" style={{ height: '100%', minHeight: '300px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-muted)' }}>
                  {status === 'running' ? 'Running agent...' : 'Awaiting input payload...'}
                </div>
              )}
            </div>
          </div>
        </>
      ) : (
        <AnalyticsTab />
      )}
    </div>
  )
}
